services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_app_db
    env_file:
      - .env.development
    environment:
      - POSTGRES_DB=appipuc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
  
volumes:
  pgdata: