version: '3.8'

services:
  # ---------------------------------------------
  # 1. CONTENEDOR DE BASE DE DATOS (PostgreSQL)
  # ---------------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: postgres_app_db
    env_file:
      - .env.development
    environment:
      - POSTGRES_DB=appipuc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"

  # ---------------------------------------------
  # 2. CONTENEDOR DE LA API (FastAPI)
  # ---------------------------------------------
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_ipuc_dev
    env_file:
      - .env.development
    expose:
      - "8000"          # solo visible dentro de la red docker, no en el host
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "5000:80"        # este es el único puerto que sale al host
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - api

volumes:
  pgdata: